### ISSUE TITLE
remove bottom navigation bar from when it isn't map, rank-board, or camera 

### ISSUE THREAD

**Issue by kezzayuno** [CMPUT301W22T00/QRHunt#109]

**Comment by Mattwmaster58** [comment]
you're referring to android UI, not our own bottom nav correct?

**Comment by kezzayuno** [comment]
If you saw the video I had shared, when you're in Settings, Player Profile--the bottom navigation is still there but I think in the UI Mock Ups, the bottom navigation is only on the Camera, Map, and Rank Board fragments
