### ISSUE TITLE
fix UML bottom navigation background color

### ISSUE THREAD

**Issue by kezzayuno** [CMPUT301W22T00/QRHunt#130]
Currently, it has a "lighter" inner rectangle which I don't know why that is or how to fix it right now.

![weird](https://user-images.githubusercontent.com/80931169/158045649-2073b487-bd52-4c01-99c2-07bfa43a272b.PNG)

**Comment by ahanatuke** [comment]
resolved. strangest graphical thing i've ever seen, definitely we did something wrong elsewhere that caused the shadow to sit in the middle of the navigation bar. however, it doesn't affect functionality and it's fixed now. UI equivalent of doing the wrong steps to get the right answer
