### ISSUE TITLE
If player deletes account, any QR codes scanned by them are only deleted 

### ISSUE THREAD

**Issue by QueenBeta** [CMPUT301W22T00/QRHunt#149]

**Comment by Mattwmaster58** [comment]
this can be done in QRHuntCloudFunction. Is this necessary for part 3?

**Comment by kezzayuno** [comment]
If it accomplished either via db cloud functions or within the app, I would say it's done.

**Comment by Mattwmaster58** [comment]
deleting users would be simple to do with a single database call - cloud funcs need to be added to update numScanned, though
