### ISSUE TITLE
Add unique flag (which QR code is the player's highest value QR)

### ISSUE THREAD

**Issue by QueenBeta** [CMPUT301W22T00/QRHunt#164]
I first need to make the flags

**Comment by Mattwmaster58** [comment]
Where is this needed? In viewing your own and other users profile right?

**Comment by kezzayuno** [comment]
Yes! 

-- User should know what is their most unique QR code (will we have many unique QR codes?)
-- User should be see what other player's most unique QR code

**Comment by QueenBeta** [comment]
This is the same as #413
