### ISSUE TITLE
Ask for technical advice on getting a players ranking(s)

### ISSUE THREAD

**Issue by QueenBeta** [CMPUT301W22T00/QRHunt#248]

**Comment by Mattwmaster58** [comment]
approach one: get every single qr code
pros: simplest, most accurate
cons: slow (how to cache?)

approach two: store in db
pros: simple for client
cons: really complicated to try and keep running totals of everything via cloud functions

**Comment by Mattwmaster58** [comment]
do we need to be able to sort leaderboard by different criteria
