### ISSUE TITLE
When you leave another person's profile, it should go back to the search bar

### ISSUE THREAD

**Issue by kezzayuno** [CMPUT301W22T00/QRHunt#354]

**Comment by QueenBeta** [comment]
is this in the user stories or specs? because in the storyboards, I just have it go back to the user's main screen if they leave someone's profile page after they've searched that user

**Comment by Mattwmaster58** [comment]
i'd prefer back to search, makes way more sense. WE're not trying to replicate the beartracks way of doing UX
