### ISSUE TITLE
fix XML for QR profile

### ISSUE THREAD

**Issue by ahanatuke** [CMPUT301W22T00/QRHunt#362]
something with the colours is messed up and it's pretty unreadable
![image](https://user-images.githubusercontent.com/97193637/161351813-f62549c9-2149-4a10-9c91-771a1844196d.png)

**Comment by QueenBeta** [comment]
looks like the opacity for the background is missing

**Comment by QueenBeta** [comment]
we can't change the opacity of the background w/o changing the opacity of everything contained inside, b/c the background is a nested scroll view
