### ISSUE TITLE
Bottom Sheet Nav - isn't being carried to leaderboard, search, player profile, and QR profile

### ISSUE THREAD

**Issue by QueenBeta** [CMPUT301W22T00/QRHunt#396]

**Comment by ahanatuke** [comment]
I think it shouldn't be carried to QR profile, but the other 3 I'm not sure about. All 3 of those involve scrolling, do you think we should carry the sheet, or could having the scroll view there make it look strange?

**Comment by ahanatuke** [comment]
not ideal fix, but good enough
