### ISSUE TITLE
Make activity icon change to "highlight" version if on that activity

### ISSUE THREAD

**Issue by QueenBeta** [CMPUT301W22T00/QRHunt#397]

**Comment by ahanatuke** [comment]
Do you want me to look at doing this manually with tint? Might save you some time

**Comment by QueenBeta** [comment]
> Do you want me to look at doing this manually with tint? Might save you some time

I've already uploaded the highlighted icons, so we just to replaced the icons with their highlighted version whenever the player is on a specific activity
