### ISSUE TITLE
Flags made and functioning for all purposes (self profile and viewing others and map)

### ISSUE THREAD

**Issue by kezzayuno** [CMPUT301W22T00/QRHunt#413]

**Comment by QueenBeta** [comment]
All flags are in place, you can start adding their functionality @Holy-Hero

**Comment by QueenBeta** [comment]
Flags are in 
- After scan window
- QR library
- QR profile
- Map QR callout

**Comment by QueenBeta** [comment]
Scanned flag (the solid blue w/a checkmark) only appear when the user (you) view other player's (other people's) profiles and/or maybe we can add them to the after scan window if the user has already scanned that QR
